print("##############################")
print("#                            #")
print("#    Muhammad Aulia Rasyid   #")
print("#       2210817210028        #")
print("#                            #")
print("##############################")
